from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt


class DocumentGenerator:

    OUTPUT_DIR = Path("generated_docs")

    def __init__(self):
        self.OUTPUT_DIR.mkdir(exist_ok=True)

    def generate(
        self,
        title: str,
        document_type: str,
        assumptions: list[str],
        sections: dict[str, str]
    ) -> str:

        document = Document()

        # -------------------------
        # Title
        # -------------------------

        heading = document.add_heading(title, level=0)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        subtitle = document.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = subtitle.add_run(document_type)
        run.bold = True
        run.font.size = Pt(12)

        date = document.add_paragraph()
        date.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date.add_run(
            f"Generated on {datetime.now().strftime('%d %B %Y %I:%M %p')}"
        )

        document.add_page_break()

        # -------------------------
        # Assumptions
        # -------------------------

        if assumptions:
            document.add_heading("Assumptions", level=1)

            for assumption in assumptions:
                document.add_paragraph(
                    assumption,
                    style="List Bullet"
                )

        # -------------------------
        # Sections
        # -------------------------

        for section, content in sections.items():

            document.add_heading(section, level=1)

            document.add_paragraph(content)

        # -------------------------
        # Footer
        # -------------------------

        section = document.sections[0]

        footer = section.footer

        footer.paragraphs[0].text = (
            "Generated by Autonomous AI Document Agent"
        )

        filename = (
            title.lower()
            .replace(" ", "_")
            .replace("/", "_")
        )

        filepath = self.OUTPUT_DIR / f"{filename}.docx"

        document.save(filepath)

        return str(filepath)